# Generated by Django 4.2 on 2024-05-30 12:27

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.uuid_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='شماره تماس')),
                ('number_id', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[account.models.validate_numeric], verbose_name='کدملی')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('is_mentor', models.BooleanField(default=False, verbose_name='مربی')),
                ('is_team_member', models.BooleanField(default=False, verbose_name='عضو تیم')),
                ('is_investor', models.BooleanField(default=False, verbose_name='سرمایه گذار')),
                ('is_company', models.BooleanField(default=False, verbose_name='شرکت')),
                ('degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدرک تحصیلی')),
                ('college_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام دانشگاه')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('type', models.CharField(choices=[('t', 'فنی'), ('b', 'بیزنسی')], default='t', max_length=1, verbose_name='نقش شما')),
                ('is_accelerator_experience', models.CharField(choices=[('y', 'بله'), ('n', 'خیر')], default='n', max_length=1, verbose_name='تجربه شرکت در برنامه شتابدهی داشته اید؟')),
                ('is_startup_experience', models.CharField(choices=[('m', 'عضو یک استارت\u200cآپ بود ام'), ('c', 'یک استارت\u200cآپ داشته ام'), ('n', 'هیچ تجربه ای ندارم')], default='n', max_length=1, verbose_name='عضو استارت آپی بوده اید؟ یا استارت آپی داشته اید؟')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='زمینه تخصصی شما')),
                ('why_us', models.TextField(blank=True, default='', null=True, verbose_name='علت درخواست شما برای برنامه شتابدهی')),
                ('bio', models.TextField(blank=True, default='', null=True, verbose_name='بیوگرافی')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeanCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('data', models.JSONField(verbose_name='اطلاعات')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'بوم کسب و کار',
                'verbose_name_plural': 'بوم های کسب و کار',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('from_date', models.DateField(verbose_name='از تاریخ')),
                ('to_date', models.DateField(verbose_name='تا تاریخ')),
                ('topic', models.CharField(max_length=255, verbose_name='عنوان شغلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('f', 'تمام وقت'), ('p', 'پاره وقت'), ('j', 'پروژه')], default='f', max_length=1, verbose_name='نوع')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_work_experience', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سابقه کاری ها',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='ساعت')),
                ('topic', models.CharField(max_length=255, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('w', 'در انتظار برسی مربی'), ('a', 'فعال'), ('d', 'انجام شده'), ('c', 'کنسل توسط کاربر'), ('r', 'ردشدن توسط مربی')], default='w', max_length=1, verbose_name='وضعیت')),
                ('rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='نمره')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_of_meeting', to=settings.AUTH_USER_MODEL, verbose_name='مربی')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسه ها',
            },
        ),
    ]
