# Generated by Django 4.2 on 2024-05-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_accelerator_experience',
            field=models.CharField(choices=[('y', 'داشته ام'), ('n', 'نداشته ام')], default='n', max_length=1, verbose_name='تجربه شرکت در برنامه شتابدهی داشته اید؟'),
        ),
    ]
