# Generated by Django 4.2 on 2024-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_content_collections_collection_contents'),
        ('account', '0002_user_age_user_interests_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, to='content.collection', verbose_name='مجموعه های کاربر'),
        ),
    ]
