# Generated by Django 4.2 on 2024-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('content', '0008_remove_content_collections_collection_contents'),
        ('account', '0003_user_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collections_of_user', to='content.collection', verbose_name='مجموعه های کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests_of_user', to='subject.subject', verbose_name='علاقه مندی ها'),
        ),
    ]
