# Generated by Django 4.2 on 2024-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_city_alter_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_specialties',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='دیگر تخصص های شما'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('d', 'دیپلم'), ('k', 'کاردانی'), ('l', 'کارشناسی'), ('f', 'کارشناسی ارشد'), ('o', 'دکترا')], default='d', max_length=1, verbose_name='مقطع تحصیلی'),
        ),
    ]
