# Generated by Django 4.2 on 2024-02-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_collections_alter_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='مربی؟'),
        ),
    ]
