# Generated by Django 4.2 on 2024-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_other_specialties_alter_user_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_is_accelerator_experience',
            field=models.JSONField(blank=True, null=True, verbose_name='اطلاعات مربوط به برنامه شتابدهی شرکت کرده توسط کابر'),
        ),
        migrations.AddField(
            model_name='user',
            name='if_is_startup_experience',
            field=models.JSONField(blank=True, null=True, verbose_name='اطلاعات مربوط به تجربه استارتاپی کابر'),
        ),
    ]
