# Generated by Django 4.2 on 2024-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_product_description'),
        ('account', '0005_user_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_to_company',
            field=models.ManyToManyField(blank=True, to='company.company', verbose_name='دسترسی به شرکت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='نشان میدهد که کاربر میتواند در سایت با عنوان نقش مربی فعالیت کند یا خیر.', verbose_name='مربی'),
        ),
    ]
