# Generated by Django 4.2 on 2024-06-01 14:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_if_is_accelerator_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=account.models.resume_directory_path, verbose_name='رزومه'),
        ),
    ]
