# Generated by Django 4.2 on 2024-02-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_access_to_company_alter_user_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_medals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
