# Generated by Django 4.2 on 2024-02-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_received_medals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='received_medals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
