# Generated by Django 4.2 on 2024-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('c', 'کنجکاو'), ('e', 'کارآفرین')], max_length=1, null=True, verbose_name='نوع کاربر'),
        ),
    ]
