# Generated by Django 4.2 on 2024-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_is_startup_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programming_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='زبانه برنامه نویسی تخصصی شما'),
        ),
    ]
