# Generated by Django 4.2 on 2024-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('account', '0011_user_access_to_team_user_is_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='abilities_of_user', to='subject.subject', verbose_name='توانایی ها'),
        ),
    ]
