# Generated by Django 4.2 on 2024-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_product_options'),
        ('account', '0012_user_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collections',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_to_company',
            field=models.ManyToManyField(blank=True, help_text='در صورتی که یک کارمند شرکت میباشد، دسترسی به یک شرکت را برای او فراهم کنید.', to='company.company', verbose_name='دسترسی به شرکت'),
        ),
    ]
