# Generated by Django 4.2 on 2024-06-09 00:24

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='why_us_video',
            field=models.FileField(blank=True, null=True, upload_to=account.models.why_us_directory_path, verbose_name='توضیحات کوتاه شما به صورت فیلم'),
        ),
    ]
