# Generated by Django 4.2 on 2024-03-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_startupteam_collections_and_more'),
        ('account', '0013_remove_user_collections_alter_user_access_to_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_to_team',
        ),
        migrations.AddField(
            model_name='user',
            name='access_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.startupteam', verbose_name='دسترسی به تیم'),
        ),
    ]
