# Generated by Django 4.2 on 2024-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_why_us_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='داور'),
        ),
        migrations.AddField(
            model_name='user',
            name='referee_type',
            field=models.CharField(choices=[('i', 'داور ایده'), ('t', 'تیم'), ('f', 'دسترسی کامل')], default='i', max_length=4, verbose_name='نوع داور'),
        ),
    ]
