# Generated by Django 4.2 on 2024-03-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_access_to_team_user_access_to_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_to_team',
        ),
    ]
