# Generated by Django 4.2 on 2024-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_is_referee_user_referee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referee_validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دسترسی داور تا'),
        ),
    ]
