# Generated by Django 4.2 on 2024-03-10 07:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_access_to_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=django_quill.fields.QuillField(default='', verbose_name='بیوگرافی'),
        ),
    ]
