# Generated by Django 4.2 on 2024-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('account', '0015_user_referee_validity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referee_type',
        ),
        migrations.AddField(
            model_name='user',
            name='referee_type',
            field=models.ManyToManyField(blank=True, to='assessment.category', verbose_name='دسترسی های کاربر'),
        ),
    ]
