# Generated by Django 4.2 on 2024-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_question_category'),
        ('account', '0016_remove_user_referee_type_user_referee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referee_type',
            field=models.ManyToManyField(blank=True, to='assessment.category', verbose_name='دسته بندی داور'),
        ),
    ]
