# Generated by Django 4.2 on 2024-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_referee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_nda',
            field=models.BooleanField(default=True, verbose_name='پذیرش قوانین و مقرارت سایت.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('t', 'توسعه دهنده تکنولوژی'), ('b', 'توسعه دهنده کسب\u200cوکار')], default='t', max_length=1, verbose_name='نقش شما'),
        ),
    ]
