# Generated by Django 4.2 on 2024-06-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_leancanvas_uuid_alter_meeting_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'مرد'), ('f', 'زن'), ('o', 'سایر')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
