# Generated by Django 4.2 on 2024-03-10 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='نمره'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('w', 'در انتظار برسی مربی'), ('a', 'فعال'), ('d', 'انجام شده'), ('c', 'کنسل توسط کاربر'), ('r', 'ردشدن توسط مربی')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
    ]
