# Generated by Django 4.2 on 2024-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_meeting_rate_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('w', 'در انتظار برسی مربی'), ('a', 'فعال'), ('d', 'انجام شده'), ('c', 'کنسل توسط کاربر'), ('r', 'ردشدن توسط مربی')], default='w', max_length=1, verbose_name='وضعیت'),
        ),
    ]
