# Generated by Django 4.2 on 2024-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('d', 'دیپلم'), ('k', 'کاردانی'), ('l', 'کارشناسی'), ('f', 'کارشناسی ارشد'), ('o', 'دکترا')], max_length=1, null=True, verbose_name='مقطع تحصیلی'),
        ),
    ]
