# Generated by Django 4.2 on 2024-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='موضوع'),
        ),
    ]
