# Generated by Django 4.2 on 2024-03-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_meeting_description_alter_meeting_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسه ها'},
        ),
    ]
