# Generated by Django 4.2 on 2024-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_product_options'),
        ('account', '0024_meeting_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_to_center',
            field=models.ManyToManyField(blank=True, help_text='در صورتی که یک ادمین مرکز میباشد، دسترسی به یک مرکز را برای او فراهم کنید.', to='company.center', verbose_name='دسترسی به مرکز'),
        ),
    ]
