# Generated by Django 4.2 on 2024-03-25 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('from_date', models.DateField(verbose_name='از تاریخ')),
                ('to_date', models.DateField(verbose_name='تا تاریخ')),
                ('topic', models.CharField(max_length=255, verbose_name='عنوان شغلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('f', 'تمام وقت'), ('p', 'پاره وقت'), ('j', 'پروژه')], default='f', max_length=1, verbose_name='نوع')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_work_experience', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سابقه کاری ها',
            },
        ),
    ]
