# Generated by Django 4.2 on 2024-04-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_center_teams'),
        ('account', '0027_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_to_center',
        ),
        migrations.AddField(
            model_name='user',
            name='access_to_center',
            field=models.ForeignKey(blank=True, help_text='در صورتی که یک ادمین مرکز میباشد، دسترسی به یک مرکز را برای او فراهم کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.center', verbose_name='دسترسی به مرکز'),
        ),
    ]
