# Generated by Django 4.2 on 2024-04-20 15:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_user_access_to_center_user_access_to_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_id',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[account.models.validate_numeric]),
        ),
    ]
