# Generated by Django 4.2 on 2024-04-20 15:15

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_user_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_id',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[account.models.validate_numeric], verbose_name='کدملی'),
        ),
    ]
