# Generated by Django 4.2 on 2024-04-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_center_teams'),
        ('account', '0030_alter_user_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(default=False, verbose_name='سرمایه گذار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_to_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.center', verbose_name='دسترسی به مرکز'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_to_company',
            field=models.ManyToManyField(blank=True, to='company.company', verbose_name='دسترسی به شرکت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_team_member',
            field=models.BooleanField(default=False, verbose_name='عضو تیم'),
        ),
    ]
