# Generated by Django 4.2 on 2024-05-09 10:23

from django.db import migrations, models
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_user_is_investor_alter_user_access_to_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('data', models.JSONField(verbose_name='اطلاعات')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سابقه کاری ها',
            },
        ),
    ]
