# Generated by Django 4.2 on 2024-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_leancanvas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leancanvas',
            options={'verbose_name': 'بوم کسب و کار', 'verbose_name_plural': 'بوم های کسب و کار'},
        ),
        migrations.AlterField(
            model_name='leancanvas',
            name='data',
            field=models.TextField(verbose_name='اطلاعات'),
        ),
    ]
