# Generated by Django 4.2 on 2024-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_leancanvas_options_alter_leancanvas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leancanvas',
            name='data',
            field=models.JSONField(verbose_name='اطلاعات'),
        ),
    ]
