# Generated by Django 4.2 on 2024-04-27 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import investor.models
import utils.uuid_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام صندوق')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='حجم صندوق')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[investor.models.validate_is_investor], verbose_name='سرمایه گذار')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق ها',
            },
        ),
    ]
