# Generated by Django 4.2 on 2024-04-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import investor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0003_investorfound_delete_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorfound',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_of_investor', to=settings.AUTH_USER_MODEL, validators=[investor.models.validate_is_investor], verbose_name='سرمایه گذار'),
        ),
    ]
