# Generated by Django 4.2 on 2024-05-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team.models
import utils.uuid_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='StartUpTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام تیم')),
                ('status', models.CharField(choices=[('a', 'فعال'), ('i', 'غیر فعال')], default='a', max_length=1, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='بیوگرافی تیم')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.category', verbose_name='دسته بندی زمینه فعالیت')),
                ('team_members', models.ManyToManyField(blank=True, related_name='members_of_team', to=settings.AUTH_USER_MODEL, verbose_name='اعضای تیم')),
                ('team_mentors', models.ManyToManyField(blank=True, related_name='mentors_of_team', to=settings.AUTH_USER_MODEL, verbose_name='مربی های تیم')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('user_number_id', models.CharField(default=0, max_length=10, validators=[team.models.validate_numeric], verbose_name='کد ملی فرد')),
                ('temporary_name', models.CharField(default='بدون نام', max_length=255, verbose_name='نام و نام خانوادگی')),
                ('is_coordinator', models.BooleanField(default=False, verbose_name='هماهنگ کننده؟')),
                ('is_owner', models.BooleanField(default=False, verbose_name='سازنده این تیم؟')),
                ('user_validation_code', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_team_member', to='team.startupteam', verbose_name='تیم')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_team_member', to=settings.AUTH_USER_MODEL, verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'عضو های تیم',
            },
        ),
        migrations.CreateModel(
            name='RoadRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام تیم')),
                ('status', models.CharField(choices=[('w', 'عدم برسی شتابدهنده'), ('p', 'درحال برسی شتابدهنده'), ('a', 'تایید شده'), ('r', 'رد شده'), ('c', 'نیاز به اصلاح توسط شما')], default='w', max_length=1, verbose_name='وضعیت')),
                ('client_last_response_date', models.DateField(blank=True, null=True, verbose_name='زمان آخرین تغییر توسط کاربر')),
                ('accelerator_last_response_date', models.DateField(blank=True, null=True, verbose_name='زمان آخرین واکنش توسط شتابدهنده')),
                ('status_user_state', models.CharField(choices=[('m', 'تیم ممبر'), ('c', 'هماهنگ کننده'), ('i', 'شخصی'), ('t', 'تیمی'), ('f', 'ثبت نام کامل')], default='w', max_length=1, verbose_name='وضعیت ثبت نام کاربر')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_of_road_registration', to='content.road', verbose_name='مسیر')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_of_road_registration', to='team.startupteam', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_road_registration', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت نام مسیر آموزشی',
                'verbose_name_plural': 'ثبت نام مسیرهای آموزشی',
            },
        ),
    ]
