# Generated by Django 4.2 on 2024-03-03 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0019_alter_content_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=team.models.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='StartUpTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=team.models.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام تیم')),
                ('status', models.CharField(choices=[('a', 'فعال'), ('i', 'غیر فعال')], default='a', max_length=1)),
                ('description', models.TextField(verbose_name='بیوگرافی تیم')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.category', verbose_name='دسته بندی زمینه فعالیت')),
                ('collections', models.ManyToManyField(blank=True, related_name='collections_of_team', to='content.collection', verbose_name='مجموعه های تیم')),
                ('team_members', models.ManyToManyField(blank=True, related_name='members_of_team', to=settings.AUTH_USER_MODEL, verbose_name='اعضای تیم')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
            },
        ),
    ]
