# Generated by Django 4.2 on 2024-03-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_content_content'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupteam',
            name='collections',
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('i', 'غیر فعال')], default='a', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_collection_order', to='content.collection', verbose_name='مجموعه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_collection_order', to='team.startupteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'ترتیب مجموعه',
                'verbose_name_plural': 'ترتیب مجموعه ها',
                'ordering': ['row_number'],
            },
        ),
    ]
