# Generated by Django 4.2 on 2024-05-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status_user_state',
            field=models.CharField(choices=[('1', 'ثبت اطلاعات اولیه'), ('2t', 'به عنوان تیم'), ('2i', 'به عنوان فرد')], default='۱', max_length=2, verbose_name='وضعیت ثبت نام کاربر'),
        ),
    ]
