# Generated by Django 4.2 on 2024-03-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_startupteam_collections_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionOrder',
        ),
    ]
