# Generated by Django 4.2 on 2024-05-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_roadregistration_status_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupteam',
            name='category',
            field=models.CharField(max_length=255, verbose_name='دسته بندی زمینه فعالیت'),
        ),
    ]
