# Generated by Django 4.2 on 2024-03-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_plan_has_team_remove_plan_user_plan_status'),
        ('team', '0003_delete_collectionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupteam',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan', verbose_name='ایده/طرح تیم'),
        ),
    ]
