# Generated by Django 4.2 on 2024-03-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_startupteam_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupteam',
            name='plan',
        ),
    ]
