# Generated by Django 4.2 on 2024-05-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_startupteam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='temporary_name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user_number_id',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user_validation_code',
        ),
    ]
