# Generated by Django 4.2 on 2024-03-05 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0005_remove_startupteam_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupteam',
            name='team_mentors',
            field=models.ManyToManyField(blank=True, related_name='mentors_of_team', to=settings.AUTH_USER_MODEL, verbose_name='مربی های تیم'),
        ),
    ]
