# Generated by Django 4.2 on 2024-04-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_roadregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='accelerator_last_response_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان آخرین واکنش توسط شتابدهنده'),
        ),
        migrations.AlterField(
            model_name='roadregistration',
            name='client_last_response_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان آخرین تغییر توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='roadregistration',
            name='status',
            field=models.CharField(choices=[('w', 'در انتظار برسی'), ('p', 'درحال برسی'), ('a', 'تایید شده'), ('r', 'رد شده'), ('c', 'نیاز به برسی')], default='w', max_length=1, verbose_name='وضعیت'),
        ),
    ]
