# Generated by Django 4.2 on 2024-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_roadregistration_team_or_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadregistration',
            name='validity_pride_days',
            field=models.PositiveIntegerField(default=10, verbose_name='مهلت تکمیل درخواست (به روز)'),
        ),
    ]
