# Generated by Django 4.2 on 2024-04-13 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0008_alter_roadregistration_accelerator_last_response_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_road_registration', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
