# Generated by Django 4.2 on 2024-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_roadregistration_validity_pride_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status_user_state',
            field=models.CharField(choices=[('bc', 'اضافه شده توسط هماهنگ کننده'), ('0', 'درحال تکمیل ثبت نام'), ('1', 'تکمیل ثبت نام اولیه'), ('f', 'ثبت نام کامل')], default='۱', max_length=2, verbose_name='وضعیت ثبت نام کاربر'),
        ),
        migrations.AlterField(
            model_name='roadregistration',
            name='team_or_individual',
            field=models.CharField(choices=[('t', 'تیم'), ('i', 'فرد'), ('a', 'تیم (اضافه شده توسط هماهنگ کننده)')], default='t', max_length=1, verbose_name='تیم یا فرد؟'),
        ),
    ]
