# Generated by Django 4.2 on 2024-04-14 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_road_holders_road_sponsors'),
        ('team', '0009_alter_roadregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_of_road_registration', to='content.road', verbose_name='مسیر'),
        ),
        migrations.AlterField(
            model_name='roadregistration',
            name='status',
            field=models.CharField(choices=[('w', 'در انتظار'), ('p', 'درحال برسی'), ('a', 'تایید شده'), ('r', 'رد شده'), ('c', 'نیاز اصلاح')], default='w', max_length=1, verbose_name='وضعیت'),
        ),
    ]
