# Generated by Django 4.2 on 2024-06-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_roadregistration_status_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status',
            field=models.CharField(choices=[('n', 'نیاز به تکمیل اطلاعات'), ('w', 'عدم برسی شتابدهنده'), ('p', 'درحال برسی شتابدهنده'), ('a', 'تایید شده'), ('r', 'رد شده'), ('c', 'نیاز به اصلاح توسط شما')], default='w', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='roadregistration',
            name='status_user_state',
            field=models.CharField(choices=[('2', 'مرحله دوم تکمیل ثبت نام'), ('3', 'مرحله سوم تکمیل ثبت نام'), ('4', 'مرحله چهارم تکمیل ثبت نام'), ('5', 'ثبت نام کامل')], default='۱', max_length=2, verbose_name='وضعیت ثبت نام کاربر'),
        ),
    ]
