# Generated by Django 4.2 on 2024-04-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'عضو تیم', 'verbose_name_plural': 'عضو های تیم'},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='creator',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.startupteam', verbose_name='تیم'),
        ),
    ]
