# Generated by Django 4.2 on 2024-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_roadregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status',
            field=models.CharField(choices=[('n', 'شما نیاز به تکمیل فرایند ثبت\u200cنام خود دارید'), ('w', 'درخواست شما توسط برگزار کننده هنوز بررسی نشده است'), ('p', 'درخواست شما در حال بررسی توسط برگزارکننده می\u200cباشد'), ('a', 'پذیرش شما در برنامه تایید شده است'), ('r', 'درخواست شما رد شده'), ('c', 'شما برای تکمیل فرایند ثبت\u200cنام نیاز به اصلاح درخواست و اطلاعات خود دارید')], default='n', max_length=1, verbose_name='وضعیت'),
        ),
    ]
