# Generated by Django 4.2 on 2024-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_teammember_options_remove_teammember_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='هماهنگ کننده؟'),
        ),
    ]
