# Generated by Django 4.2 on 2024-06-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_roadregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupteam',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='startupteam',
            name='team_mentors',
        ),
    ]
