# Generated by Django 4.2 on 2024-04-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_teammember_user_alter_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='سازنده این تیم؟'),
        ),
    ]
