# Generated by Django 4.2 on 2024-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_alter_category_uuid_alter_roadregistration_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadregistration',
            name='validity_pride_days_for_challenge',
            field=models.PositiveIntegerField(default=5, verbose_name='مهلت تکمیل درخواست (به روز)'),
        ),
    ]
