# Generated by Django 4.2 on 2024-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_roadregistration_validity_pride_days_for_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='validity_pride_days_for_challenge',
            field=models.PositiveIntegerField(default=3, verbose_name='مهلت تکمیل درخواست (به روز)'),
        ),
    ]
