# Generated by Django 4.2 on 2024-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_alter_roadregistration_validity_pride_days_for_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='validity_pride_days_for_challenge',
            field=models.PositiveIntegerField(default=3, verbose_name='مهلت تکمیل چالش (به روز)'),
        ),
    ]
