# Generated by Django 4.2 on 2024-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_alter_teammember_user_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='temporary_name',
            field=models.CharField(default='بدون نام', max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
    ]
