# Generated by Django 4.2 on 2024-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_alter_roadregistration_validity_pride_days_for_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status_user_state',
            field=models.CharField(choices=[('2', 'مرحله دوم تکمیل ثبت نام'), ('3', 'مرحله سوم تکمیل ثبت نام'), ('4', 'مرحله چهارم تکمیل ثبت نام'), ('5', 'ثبت نام کامل')], default='2', max_length=2, verbose_name='وضعیت ثبت نام کاربر'),
        ),
    ]
