# Generated by Django 4.2 on 2024-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_teammember_temporary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='user_validation_code',
            field=models.CharField(blank=True, default='6jusr', editable=False, max_length=15, unique=True),
        ),
    ]
