# Generated by Django 4.2 on 2024-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_teammember_user_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='user_validation_code',
            field=models.CharField(blank=True, default='v1cjv1hsaoaiu1g', editable=False, max_length=15, unique=True),
        ),
    ]
