# Generated by Django 4.2 on 2024-04-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_alter_teammember_user_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='user_validation_code',
            field=models.CharField(blank=True, default='q27ppldjlo0hn1r', editable=False, max_length=15, unique=True),
        ),
    ]
