# Generated by Django 4.2 on 2024-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_alter_teammember_user_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='user_validation_code',
            field=models.CharField(blank=True, default='zhgahvcmijvpkqu', editable=False, max_length=15, unique=True),
        ),
    ]
