# Generated by Django 4.2 on 2024-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_alter_teammember_user_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='user_validation_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
