# Generated by Django 4.2 on 2024-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0025_alter_teammember_user_validation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadregistration',
            name='status_user_state',
            field=models.CharField(choices=[('w', 'در انتظار'), ('p', 'درحال برسی'), ('a', 'تایید شده'), ('r', 'رد شده'), ('c', 'نیاز اصلاح')], default='w', max_length=1, verbose_name='وضعیت ثبت نام کاربر'),
        ),
    ]
