# Generated by Django 4.2 on 2024-05-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0026_roadregistration_status_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status_user_state',
            field=models.CharField(choices=[('m', 'تیم ممبر'), ('c', 'هماهنگ کننده'), ('i', 'شخصی'), ('t', 'تیمی'), ('f', 'ثبت نام کامل')], default='w', max_length=1, verbose_name='وضعیت ثبت نام کاربر'),
        ),
    ]
