# Generated by Django 4.2 on 2024-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_alter_roadregistration_status_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status',
            field=models.CharField(choices=[('w', 'در انتظار تایید شتابدهنده'), ('p', 'درحال برسی توسط شتابدهنده'), ('a', 'تایید شده'), ('r', 'رد شده توسط شتابدهنده'), ('c', 'نیاز به اصلاح توسط شما')], default='w', max_length=1, verbose_name='وضعیت'),
        ),
    ]
