# Generated by Django 4.2 on 2024-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0028_alter_roadregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadregistration',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام تیم'),
        ),
    ]
