# Generated by Django 4.2 on 2024-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0029_roadregistration_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadregistration',
            name='status',
            field=models.CharField(choices=[('w', 'عدم برسی شتابدهنده'), ('p', 'درحال برسی شتابدهنده'), ('a', 'تایید شده'), ('r', 'رد شده'), ('c', 'نیاز به اصلاح توسط شما')], default='w', max_length=1, verbose_name='وضعیت'),
        ),
    ]
