# Generated by Django 4.2 on 2024-02-18 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='متن')),
                ('is_valid', models.BooleanField(default=False, verbose_name='درست بودن')),
            ],
            options={
                'verbose_name': 'جواب',
                'verbose_name_plural': 'جواب ها',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=quiz.models.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='عنوان')),
                ('medals', models.PositiveIntegerField(default=0, verbose_name='مدال')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='متن')),
                ('answers', models.ManyToManyField(to='quiz.answer', verbose_name='گزینه ها')),
            ],
            options={
                'verbose_name': 'سوآل',
                'verbose_name_plural': 'سوآل ها',
            },
        ),
        migrations.CreateModel(
            name='UserExamAnsewrHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansewr_history_of_answer', to='quiz.answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansewr_history_of_exam', to='quiz.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansewr_history_of_question', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansewr_history_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='quiz.question', verbose_name='سوال ها'),
        ),
    ]
