# Generated by Django 4.2 on 2024-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistertask',
            name='type',
            field=models.CharField(choices=[('t', 'فنی'), ('b', 'بیزنسی')], default='t', max_length=1, verbose_name='نوع'),
        ),
    ]
