# Generated by Django 4.2 on 2024-06-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_preregistertask_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltest',
            options={'verbose_name': 'چالش مهارت نرم', 'verbose_name_plural': 'آزمون های شخصیت'},
        ),
    ]
