# Generated by Django 4.2 on 2024-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_created_time_answer_last_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='userexamansewrhistory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='userexamansewrhistory',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی'),
        ),
    ]
