# Generated by Django 4.2 on 2024-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexamansewrhistory',
            options={'verbose_name': 'پاسخ ها کاربر', 'verbose_name_plural': 'پاسخ های کاربر '},
        ),
    ]
