# Generated by Django 4.2 on 2024-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_personaltest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltest',
            name='assessment_obj_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaltest',
            name='assessment_obj_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaltest',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
