# Generated by Django 4.2 on 2024-04-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_center_teams'),
        ('quiz', '0004_alter_userexamansewrhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_exam', to='company.center', verbose_name='برگزارکننده'),
        ),
    ]
