# Generated by Django 4.2 on 2024-04-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_center_teams'),
        ('quiz', '0005_exam_accelerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_answer', to='company.center', verbose_name='برگزارکننده'),
        ),
        migrations.AddField(
            model_name='question',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_question', to='company.center', verbose_name='برگزارکننده'),
        ),
    ]
