# Generated by Django 4.2 on 2024-06-24 23:53

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_road_pre_register_task_for_business_side_and_more'),
        ('company', '0003_center_referees'),
        ('quiz', '0005_personaltest_final_user_result_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistertaskresponse',
            options={'verbose_name': 'پاسخ کاربر به سوال های آزمون', 'verbose_name_plural': 'پاسخ های کاربر به سوال های آزمون'},
        ),
        migrations.RemoveField(
            model_name='preregistertask',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='preregistertask',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='preregistertask',
            name='text',
        ),
        migrations.RemoveField(
            model_name='preregistertaskresponse',
            name='file',
        ),
        migrations.RemoveField(
            model_name='preregistertaskresponse',
            name='status',
        ),
        migrations.RemoveField(
            model_name='preregistertaskresponse',
            name='task',
        ),
        migrations.RemoveField(
            model_name='preregistertaskresponse',
            name='title',
        ),
        migrations.AlterField(
            model_name='preregistertaskresponse',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_of_pre_register_task_response', to='content.road', verbose_name='مسیر'),
        ),
        migrations.CreateModel(
            name='PreRegisterTaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', django_quill.fields.QuillField(verbose_name='عنوان')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی')),
                ('accelerator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_pre_register_task_question', to='company.center', verbose_name='برگزارکننده')),
                ('pre_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_register_of_pre_register_task_question', to='quiz.preregistertask', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال های آزمون پیش ثبت نام',
                'verbose_name_plural': 'سوال های آزمون های پیش ثبت نام',
            },
        ),
        migrations.AddField(
            model_name='preregistertaskresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_of_pre_register_task_response', to='quiz.preregistertaskquestion', verbose_name='سوال'),
        ),
    ]
