# Generated by Django 4.2 on 2024-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_answer_accelerator_question_accelerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.question', verbose_name='سوال ها'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.answer', verbose_name='گزینه ها'),
        ),
    ]
