# Generated by Django 4.2 on 2024-04-07 12:22

from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_road_expiration_date_road_start_date'),
        ('quiz', '0007_alter_exam_questions_alter_question_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_exam_order', to='content.collection', verbose_name='مسیر')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_of_exam_order', to='quiz.exam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'پاسخ ها کاربر',
                'verbose_name_plural': 'پاسخ های کاربر ',
            },
        ),
    ]
