# Generated by Django 4.2 on 2024-04-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_road_expiration_date_road_start_date'),
        ('quiz', '0008_examorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examorder',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_exam_order', to='content.collection', verbose_name='فصل'),
        ),
    ]
