# Generated by Django 4.2 on 2024-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_examorder_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examorder',
            options={'verbose_name': 'ترتیب آزمون', 'verbose_name_plural': 'ترتیب آزمون ها'},
        ),
    ]
