# Generated by Django 4.2 on 2024-06-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_personaltest_final_user_result_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistertaskquestion',
            name='aparat_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک آپارات'),
        ),
    ]
