# Generated by Django 4.2 on 2024-06-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_preregistertaskquestion_aparat_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistertaskquestion',
            name='aparat_link',
        ),
        migrations.AddField(
            model_name='preregistertaskquestion',
            name='aparat_embed_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک آپارات'),
        ),
    ]
