# Generated by Django 4.2 on 2024-04-10 07:44

from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_road_publish_date'),
        ('quiz', '0011_task_taskresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_task_order', to='content.collection', verbose_name='فصل')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_of_task_order', to='quiz.task', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'ترتیب تسک',
                'verbose_name_plural': 'ترتیب تسک ها',
            },
        ),
    ]
