# Generated by Django 4.2 on 2024-06-29 01:10

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_preregistertaskquestion_aparat_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistertaskquestion',
            name='aparat_embed_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک embed آپارات'),
        ),
        migrations.AlterField(
            model_name='preregistertaskquestion',
            name='text',
            field=django_quill.fields.QuillField(verbose_name='متن سوال'),
        ),
    ]
