# Generated by Django 4.2 on 2024-04-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_taskorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskorder',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_of_task_order', to='quiz.task', verbose_name='تسک'),
        ),
    ]
