# Generated by Django 4.2 on 2024-05-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_preregistertaskresponse_preregistertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistertask',
            options={'verbose_name': 'آزمون پیش ثبت نام', 'verbose_name_plural': 'آزمون های پیش ثبت نام'},
        ),
        migrations.AlterField(
            model_name='preregistertaskresponse',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_of_pre_register_task_response', to='quiz.preregistertask', verbose_name='تسک'),
        ),
    ]
