# Generated by Django 4.2 on 2024-05-24 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0043_road_pre_register_task'),
        ('quiz', '0015_alter_preregistertask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان بروزرسانی')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_of_personal_test', to='content.road', verbose_name='مسیر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_personal_test', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آزمون شخصیت',
                'verbose_name_plural': 'آزمون های شخصیت',
            },
        ),
    ]
