# Generated by Django 4.2 on 2024-06-18 18:36

from django.db import migrations, models
import utils.uuid_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyLog',
            fields=[
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=3, verbose_name='کد وضعیت')),
                ('message', models.JSONField(verbose_name='پاسخ سرور')),
                ('send_try', models.PositiveIntegerField(verbose_name='تلاش برای ارسال')),
            ],
        ),
    ]
