# Generated by Django 4.2 on 2024-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifylog',
            name='message',
            field=models.TextField(null=True, verbose_name='پاسخ سرور'),
        ),
    ]
