# Generated by Django 4.2 on 2024-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_alter_notifylog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifylog',
            name='message',
            field=models.JSONField(null=True, verbose_name='پاسخ سرور'),
        ),
    ]
