# Generated by Django 4.2 on 2024-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0005_notifylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifylog',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم عملیات'),
        ),
    ]
