# Generated by Django 4.2 on 2024-06-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_alter_notifylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifylog',
            name='status',
            field=models.CharField(max_length=10, verbose_name='کد وضعیت'),
        ),
    ]
