# Generated by Django 4.2 on 2024-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_alter_notifylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifylog',
            name='status',
            field=models.CharField(max_length=255, verbose_name='کد وضعیت'),
        ),
    ]
