# Generated by Django 4.2 on 2024-06-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0010_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
