# Generated by Django 4.2 on 2024-01-29 14:51

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=company.models.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='اسم کسب و کار')),
                ('domain', models.URLField(max_length=255, verbose_name='دامنه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/', verbose_name='لوگو')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کسب و کار',
                'verbose_name_plural': 'کسب و کار ها',
            },
        ),
    ]
