# Generated by Django 4.2 on 2024-02-03 09:29

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=company.models.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام خدمت یا محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='مدال مورد نیاز')),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='کمپانی')),
            ],
            options={
                'verbose_name': 'خدمت یا کالا',
                'verbose_name_plural': 'خدمت ها یا کالا ها',
            },
        ),
    ]
