# Generated by Django 4.2 on 2024-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_of_center', to='team.startupteam', verbose_name='تیم های استارتاپی'),
        ),
    ]
