# Generated by Django 4.2 on 2024-06-17 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='referees',
            field=models.ManyToManyField(blank=True, related_name='referee_of_center', to=settings.AUTH_USER_MODEL, verbose_name='داور ها'),
        ),
    ]
