# Generated by Django 4.2 on 2024-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('company', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='watching_subject',
            field=models.ManyToManyField(blank=True, related_name='watching_subject_of_company', to='subject.subject', verbose_name='موضوعات زیر نظر'),
        ),
    ]
