# Generated by Django 4.2 on 2024-02-25 23:02

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_watching_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=company.models.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='اسم مرکز')),
                ('domain', models.URLField(max_length=255, verbose_name='دامنه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/', verbose_name='لوگو')),
                ('state', models.CharField(max_length=255, verbose_name='استان')),
                ('type', models.CharField(choices=[('g', 'مرکز رشد'), ('a', 'مرکز شتابدهی'), ('i', 'کارخونه نوآوری')], max_length=1, verbose_name='نوع')),
                ('activity', models.CharField(max_length=255, verbose_name='حوزه فعالیت')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مرکز',
                'verbose_name_plural': 'مراکز',
            },
        ),
    ]
