# Generated by Django 4.2 on 2024-02-26 08:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='description',
            field=django_quill.fields.QuillField(default='', verbose_name='توضیحات'),
        ),
    ]
