# Generated by Django 4.2 on 2024-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_center_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='short_description',
            field=models.TextField(default='', verbose_name='توضیحات کوتاه'),
        ),
    ]
