# Generated by Django 4.2 on 2024-03-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_center_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_time'], 'verbose_name': 'خدمت یا کالا', 'verbose_name_plural': 'خدمت ها یا کالا ها'},
        ),
    ]
