# Generated by Django 4.2 on 2024-04-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_startupteam_team_mentors'),
        ('company', '0011_alter_center_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_of_center', to='team.startupteam', verbose_name='تیم های استارتاپی'),
        ),
    ]
