# Generated by Django 4.2 on 2024-04-27 12:18

from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_productwallet_created_time_and_more'),
        ('company', '0012_alter_center_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceleratorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('accelerator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_of_accelerator', to='plan.plan', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'کیف پول محصول',
                'verbose_name_plural': 'کیف پول محصول ها',
            },
        ),
    ]
