# Generated by Django 4.2 on 2024-04-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_acceleratorfund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceleratorFund',
        ),
    ]
