# Generated by Django 4.2 on 2024-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_delete_acceleratorfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='domain',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='دامنه'),
        ),
    ]
