# Generated by Django 4.2 on 2024-05-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import utils.uuid_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='plan/logo/', verbose_name='لوگو')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='صنعت')),
                ('description', models.TextField(verbose_name='توصیف کوتاه')),
                ('text', django_quill.fields.QuillField(blank=True, default='', null=True, verbose_name='توضیحات کامل')),
                ('has_mvp', models.BooleanField(blank=True, null=True, verbose_name='دارای کمینه')),
                ('status', models.CharField(blank=True, choices=[('p', 'درحال انجام'), ('f', 'تمام شده')], default='p', max_length=1, null=True, verbose_name='وضعیت')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='user_of_likes_plan', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_of_plan', to='team.startupteam', verbose_name='تیم')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_plan', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محصول یا ایده',
                'verbose_name_plural': 'محصول ها و ایده ها',
            },
        ),
        migrations.CreateModel(
            name='ProductWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_of_product', to='plan.plan', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'کیف پول محصول',
                'verbose_name_plural': 'کیف پول محصول ها',
            },
        ),
    ]
