# Generated by Django 4.2 on 2024-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='linkdin',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='telegram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='توئیتر (ایکس)'),
        ),
    ]
