# Generated by Django 4.2 on 2024-06-08 12:32

from django.db import migrations, models
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=plan.models.user_directory_path, verbose_name='فیلم کوتاه از محصول خود'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_mvp',
            field=models.BooleanField(default=False, verbose_name='دارای کمینه'),
        ),
    ]
