# Generated by Django 4.2 on 2024-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_instagram_alter_plan_linkdin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='plan/logo/', verbose_name='لوگو'),
        ),
    ]
