# Generated by Django 4.2 on 2024-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='has_team',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('p', 'درحال انجام'), ('f', 'تمام شده')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
    ]
