# Generated by Django 4.2 on 2024-03-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0004_remove_plan_has_team_remove_plan_user_plan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_plan', to=settings.AUTH_USER_MODEL, verbose_name='تیم'),
        ),
    ]
