# Generated by Django 4.2 on 2024-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_plan_progress_status_alter_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='progress_status',
            field=models.CharField(choices=[('0', 'در حال توسعه نسخه MVP هستیم'), ('1', 'نسخه MVP آماده داریم'), ('2', 'محصول آماده به کار داریم'), ('3', 'قبلا محصول خود را به بازار ارایه کرده\u200cایم')], default='i', max_length=1, verbose_name='سطح محصول'),
        ),
    ]
