# Generated by Django 4.2 on 2024-03-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_startupteam_plan'),
        ('plan', '0005_plan_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_plan', to='team.startupteam', verbose_name='تیم'),
        ),
    ]
