# Generated by Django 4.2 on 2024-06-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_alter_plan_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='has_mvp',
        ),
    ]
