# Generated by Django 4.2 on 2024-06-25 15:35

from django.db import migrations, models
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_remove_plan_has_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='uuid',
            field=models.CharField(blank=True, default=utils.uuid_generator.random_uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='productwallet',
            name='uuid',
            field=models.CharField(blank=True, default=utils.uuid_generator.random_uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
