# Generated by Django 4.2 on 2024-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_plan_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصول ها'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(verbose_name='توصیف محصول'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام محصول'),
        ),
    ]
