# Generated by Django 4.2 on 2024-04-27 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0011_remove_plan_city_remove_plan_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'کیف پول محصول',
                'verbose_name_plural': 'کیف پول محصول ها',
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'محصول یا ایده', 'verbose_name_plural': 'محصول ها و ایده ها'},
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده (سرمایه گذار)')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_of_transaction', to='plan.productwallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش های کیف پول ها',
            },
        ),
        migrations.AddField(
            model_name='productwallet',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_of_product', to='plan.plan', verbose_name='محصول'),
        ),
    ]
