# Generated by Django 4.2 on 2024-04-27 12:18

from django.db import migrations, models
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_productwallet_alter_plan_options_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwallet',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productwallet',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productwallet',
            name='uuid',
            field=models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True),
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
