# Generated by Django 4.2 on 2024-05-20 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0013_productwallet_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_of_likes_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
