# Generated by Django 4.2 on 2024-05-21 12:39

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_alter_plan_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='has_mvp',
            field=models.BooleanField(blank=True, null=True, verbose_name='دارای کمینه'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'درحال انجام'), ('f', 'تمام شده')], default='p', max_length=1, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='text',
            field=django_quill.fields.QuillField(blank=True, default='', null=True, verbose_name='توضیحات کامل'),
        ),
    ]
