# Generated by Django 4.2 on 2024-03-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_topic_alter_subject_options_subject_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_of_subject', to='subject.topic', verbose_name='موضوع'),
        ),
    ]
