# Generated by Django 4.2 on 2024-04-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0003_alter_subject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_subject', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_topic', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_of_subject', to='subject.topic', verbose_name='موضوع'),
        ),
    ]
