# Generated by Django 4.2 on 2024-05-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import utils.uuid_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('type', models.CharField(choices=[('c', 'کنجکاو'), ('e', 'کارآفرین'), ('g', 'عمومی')], default='c', max_length=1, verbose_name='برای کاربران با نوع')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'فصل آموزشی',
                'verbose_name_plural': 'فصل های',
            },
        ),
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ترتیب فصل',
                'verbose_name_plural': 'ترتیب فصل ها',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('video_link', models.URLField(blank=True, help_text='آپارات یا یوتیوب', null=True, verbose_name='لینک ویدیو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('content', django_quill.fields.QuillField(default='', verbose_name='محتوا متنی')),
                ('medals', models.PositiveIntegerField(default=0, verbose_name='مدال')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا ها',
            },
        ),
        migrations.CreateModel(
            name='ContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ترتیب دوره',
                'verbose_name_plural': 'ترتیب دوره ها',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('poster', models.ImageField(null=True, upload_to='roads-poster/', verbose_name='پوستر')),
                ('name', models.CharField(max_length=255, verbose_name='نام مسیر')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='مکان برگزاری')),
                ('holding_method', models.CharField(choices=[('s', 'حضوری'), ('o', 'آنلاین'), ('h', 'حضوری و آنلاین')], default='h', max_length=1, verbose_name='شیوه برگزاری')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='هزینه ثبت نام')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='توضیحات کوتاه')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ شروع')),
                ('expiration_date', models.DateField(null=True, verbose_name='تاریخ پایان')),
                ('publish_date', models.DateField(null=True, verbose_name='تاریخ انتشار')),
                ('registration_deadline', models.DateField(null=True, verbose_name='مهلت ثبت نام')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('accelerator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_road', to='company.center', verbose_name='برگزارکننده')),
                ('holders', models.ManyToManyField(related_name='holders_of_road', to='company.center', verbose_name='برگزارکنندگان')),
            ],
            options={
                'verbose_name': 'مسیر',
                'verbose_name_plural': 'مسیر ها',
            },
        ),
        migrations.CreateModel(
            name='WatchedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_of_watched_content', to='content.content', verbose_name='محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_watched_content', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گام طی شده',
                'verbose_name_plural': 'گام های طی شده',
            },
        ),
        migrations.CreateModel(
            name='RoadFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('road', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_of_road', to='content.road', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'کیف پول برنامه',
                'verbose_name_plural': 'کیف پول برنامه ها',
            },
        ),
    ]
