# Generated by Django 4.2 on 2024-05-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('company', '0002_initial'),
        ('subject', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='pre_register_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_register_task_of_road', to='quiz.preregistertask', verbose_name='آزمون ورودی'),
        ),
        migrations.AddField(
            model_name='road',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsors_of_road', to='company.center', verbose_name='حمایت کنندگان'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_content_order', to='content.collection', verbose_name='فصل'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_of_content_order', to='content.content', verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='content',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_content', to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده محتوا)'),
        ),
        migrations.AddField(
            model_name='content',
            name='subjects',
            field=models.ManyToManyField(to='subject.subject', verbose_name='موضوعات مربوط'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_collection_order', to='content.collection', verbose_name='فصل'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_of_collection_order', to='content.road', verbose_name='مسیر'),
        ),
        migrations.AddField(
            model_name='collection',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_collection', to='company.center', verbose_name='برگزارکننده'),
        ),
        migrations.AddField(
            model_name='collection',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_of_collection', to='quiz.exam', verbose_name='آزمون'),
        ),
        migrations.AddField(
            model_name='collection',
            name='subjects',
            field=models.ManyToManyField(to='subject.subject', verbose_name='موضوعات'),
        ),
    ]
