# Generated by Django 5.0.1 on 2024-01-29 06:41

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_collection_uuid_alter_content_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.CharField(blank=True, default=content.models.random_uuid, editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='uuid',
            field=models.CharField(blank=True, default=content.models.random_uuid, editable=False, max_length=5, unique=True),
        ),
    ]
