# Generated by Django 4.2 on 2024-06-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_preregistertask_type'),
        ('content', '0003_road_pre_register_task_for_business_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='pre_register_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_register_task_of_road', to='quiz.preregistertask', verbose_name='آزمون ورودی برای افراد توسعه دهنده تکنولوژی'),
        ),
        migrations.AlterField(
            model_name='road',
            name='pre_register_task_for_business_side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_register_task_for_business_side_of_road', to='quiz.preregistertask', verbose_name='آزمون ورودی برای افراد توسعه دهنده کسب و کار'),
        ),
    ]
