# Generated by Django 5.0.1 on 2024-01-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_collection_uuid_alter_content_collections_and_more'),
        ('content', '0004_alter_collection_uuid_alter_content_uuid'),
    ]

    operations = [
    ]
