# Generated by Django 4.2 on 2024-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('content', '0006_content_description_alter_collection_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='subjects',
            field=models.ManyToManyField(to='subject.subject', verbose_name='موضوعات مربوط'),
        ),
        migrations.AddField(
            model_name='content',
            name='subjects',
            field=models.ManyToManyField(to='subject.subject', verbose_name='موضوعات مربوط'),
        ),
    ]
