# Generated by Django 4.2 on 2024-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_collection_subjects_content_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='contents',
            field=models.ManyToManyField(to='content.content', verbose_name='محتوا ها'),
        ),
    ]
