# Generated by Django 4.2 on 2024-02-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_watchedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='medals',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدال'),
        ),
    ]
