# Generated by Django 4.2 on 2024-02-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('content', '0011_alter_content_medals'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='آزمون'),
        ),
    ]
