# Generated by Django 4.2 on 2024-02-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_created_time_and_more'),
        ('content', '0012_collection_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='آزمون'),
        ),
    ]
