# Generated by Django 4.2 on 2024-02-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_collection_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.collection', verbose_name='مجموعه')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content', verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'ترتیب دوره',
                'verbose_name_plural': 'ترتیب دوره ها',
            },
        ),
    ]
