# Generated by Django 4.2 on 2024-02-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_contentorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentorder',
            options={'ordering': ['row_number'], 'verbose_name': 'ترتیب دوره', 'verbose_name_plural': 'ترتیب دوره ها'},
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_content_order', to='content.collection', verbose_name='مجموعه'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_of_content_order', to='content.content', verbose_name='محتوا'),
        ),
    ]
