# Generated by Django 4.2 on 2024-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_contentorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='contents',
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی'),
        ),
    ]
