# Generated by Django 4.2 on 2024-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_collection_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='row_number',
            field=models.PositiveIntegerField(default=1, verbose_name='شماره ردیف'),
        ),
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('c', 'کنجکاو'), ('e', 'کارآفرین'), ('g', 'عمومی')], default='c', max_length=1, verbose_name='برای کاربران با نوع'),
        ),
    ]
