# Generated by Django 4.2 on 2024-02-25 20:40

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_collection_row_number_collection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
