# Generated by Django 4.2 on 2024-02-25 23:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=django_quill.fields.QuillField(default='', verbose_name='محتوا متنی'),
        ),
    ]
