# Generated by Django 4.2 on 2024-03-04 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_delete_collectionorder'),
        ('content', '0019_alter_content_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='row_number',
        ),
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_collection_order', to='content.collection', verbose_name='مجموعه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_collection_order', to='team.startupteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'ترتیب مجموعه',
                'verbose_name_plural': 'ترتیب مجموعه ها',
                'ordering': ['row_number'],
            },
        ),
    ]
