# Generated by Django 4.2 on 2024-03-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_userexamansewrhistory_options'),
        ('content', '0020_remove_collection_row_number_collectionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_of_collection', to='quiz.exam', verbose_name='آزمون'),
        ),
    ]
