# Generated by Django 4.2 on 2024-03-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_product_options'),
        ('content', '0021_alter_collection_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده مجموعه)'),
        ),
        migrations.AddField(
            model_name='content',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده محتوا)'),
        ),
    ]
