# Generated by Django 4.2 on 2024-03-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_product_options'),
        ('content', '0022_collection_accelerator_content_accelerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerato_of_collection', to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده مجموعه)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerato_of_content', to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده محتوا)'),
        ),
    ]
