# Generated by Django 4.2 on 2024-03-17 08:18

from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_center_description'),
        ('content', '0023_alter_collection_accelerator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام مسیر')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('accelerator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerato_of_road', to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده مسیر)')),
                ('collections', models.ManyToManyField(blank=True, related_name='collection_of_road', to='content.collection', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'مسیر',
                'verbose_name_plural': 'مسیر ها',
            },
        ),
    ]
