# Generated by Django 4.2 on 2024-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_of_road', to='content.collection', verbose_name='مجموعه ها'),
        ),
    ]
