# Generated by Django 4.2 on 2024-03-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_center_description'),
        ('subject', '0003_alter_subject_topic'),
        ('content', '0025_alter_road_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedcontent',
            options={'verbose_name': 'گام طی شده', 'verbose_name_plural': 'گام های طی شده'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerato_of_collection', to='company.center', verbose_name='برگزارکننده'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subjects',
            field=models.ManyToManyField(to='subject.subject', verbose_name='موضوعات'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_of_content_order', to='content.collection', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='road',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerato_of_road', to='company.center', verbose_name='برگزارکننده'),
        ),
        migrations.AlterField(
            model_name='road',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_of_road', to='content.collection', verbose_name='فصل ها'),
        ),
    ]
