# Generated by Django 4.2 on 2024-03-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_watchedcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_link',
            field=models.URLField(blank=True, help_text='آپارات یا یوتیوب', null=True, verbose_name='لینک ویدیو'),
        ),
    ]
