# Generated by Django 4.2 on 2024-04-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_startupteam_team_mentors'),
        ('content', '0027_alter_content_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionorder',
            name='team',
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_of_collection_order', to='team.startupteam', verbose_name='مسیر'),
        ),
    ]
