# Generated by Django 4.2 on 2024-04-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_remove_collectionorder_team_collectionorder_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='collections',
        ),
    ]
