# Generated by Django 4.2 on 2024-04-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_road_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionorder',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_of_collection_order', to='content.road', verbose_name='مسیر'),
        ),
    ]
