# Generated by Django 4.2 on 2024-04-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_center_teams'),
        ('content', '0030_alter_collectionorder_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_collection', to='company.center', verbose_name='برگزارکننده'),
        ),
        migrations.AlterField(
            model_name='content',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_content', to='company.center', verbose_name='مرکز شتابدهنده (ایجاد کننده محتوا)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='accelerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_of_road', to='company.center', verbose_name='برگزارکننده'),
        ),
    ]
