# Generated by Django 4.2 on 2024-04-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_road_expiration_date_road_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='publish_date',
            field=models.DateField(null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
