# Generated by Django 4.2 on 2024-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_road_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
