# Generated by Django 4.2 on 2024-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_road_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='poster',
            field=models.ImageField(null=True, upload_to='roads-poster/', verbose_name='پوستر'),
        ),
    ]
