# Generated by Django 4.2 on 2024-04-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_road_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='registration_deadline',
            field=models.DateField(null=True, verbose_name='مهلت ثبت نام'),
        ),
    ]
