# Generated by Django 4.2 on 2024-04-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_road_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه'),
        ),
    ]
