# Generated by Django 4.2 on 2024-04-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_road_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='holding_method',
            field=models.CharField(default='h', max_length=1, verbose_name='شیوه برگزاری'),
        ),
        migrations.AddField(
            model_name='road',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='مکان برگزاری'),
        ),
        migrations.AlterField(
            model_name='road',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='road',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه ثبت نام'),
        ),
    ]
