# Generated by Django 4.2 on 2024-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_road_holding_method_road_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='holding_method',
            field=models.CharField(choices=[('s', 'حضوری'), ('o', 'آنلاین'), ('h', 'حضوری و آنلاین')], default='h', max_length=1, verbose_name='شیوه برگزاری'),
        ),
    ]
