# Generated by Django 4.2 on 2024-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_center_teams'),
        ('content', '0040_alter_road_holding_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='holders',
            field=models.ManyToManyField(related_name='holders_of_road', to='company.center', verbose_name='برگزارکنندگان'),
        ),
        migrations.AddField(
            model_name='road',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsors_of_road', to='company.center', verbose_name='حمایت کنندگان'),
        ),
    ]
