# Generated by Django 4.2 on 2024-04-27 14:08

from django.db import migrations, models
import django.db.models.deletion
import utils.uuid_generator


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_road_holders_road_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=utils.uuid_generator.random_uuid, editable=False, max_length=5, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('road', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_of_road', to='content.road', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'کیف پول برنامه',
                'verbose_name_plural': 'کیف پول برنامه ها',
            },
        ),
    ]
