# Generated by Django 4.2 on 2024-05-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_preregistertaskresponse_preregistertask'),
        ('content', '0042_roadfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='pre_register_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_register_task_of_road', to='quiz.preregistertask', verbose_name='آزمون ورودی'),
        ),
    ]
